export const SHOW_LIST = 'SHOW_LIST';

export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST';

export const DELETE_ITEM_TO_LIST = 'DELETE_ITEM_TO_LIST';

export const CHANGE_ACTIVE_ITEM = 'CHANGE_ACTIVE_ITEM';

export const EDIT_ITEM = 'EDIT_ITEM';

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';

export const CHANGE_PAGINATION_PREV = 'CHANGE_PAGINATION_PREV';

export const CHANGE_PAGINATION_NEXT = 'CHANGE_PAGINATION_NEXT';